aop.launcher.diagnosticStrategy = disabled
aop.launcher.diagnosticTypeExpressions = 

aop.launcher.detectTypeResolution = false

aop.launcher.dumpByteCode = false


aop.logger.includeLocation = false
aop.logger.allLogLevel = INFO


aop.globalTaskExecutor.parallel = true

aop.classScanner.acceptPackages = org.framework.aspect*
aop.classScanner.enableVerbose = false


aop.weaver.enableWeaver = true

# create AspectClassLoader for instrumenting target ClassLoader or share one if possible
aop.factory.shareAspectClassLoader = true 

# list target ClassLoaders following format 'CL1, CL2, CL3; CL2, CL4' to mark ClassLoaders might load same class
aop.factory.conflictTargetClassLoaders = org.framework.demo.classloader.RunnerClassLoader, org.framework.demo.classloader.RunnerClassLoader2
