aop.launcher.diagnosticStrategy = disabled
aop.launcher.diagnosticTypeExpressions = org.framework.demo.DemoServiceRunner

aop.launcher.typeResolutionDetected = false

aop.launcher.byteCodeDumped = false


aop.logger.locationIncluded = false
aop.logger.allLogLevel = INFO


aop.globalTaskExecutor.parallel = true

aop.classScanner.acceptPackages = org.framework.aspect*
aop.classScanner.verboseEnabled = false


aop.weaver.weaverEnabled = true

# create AspectClassLoader for instrumenting target ClassLoader or share one if possible
aop.factory.aspectClassLoaderShared = true 

# list target ClassLoaders following format 'CL1, CL2, CL3; CL2, CL4' to mark ClassLoaders might load same class
aop.factory.conflictTargetClassLoaders = org.framework.demo.RunnerClassLoader, org.framework.demo.RunnerClassLoader2
