# override settings in aop.properties

aop.factory.factoryClassLoaderExpressions = \
                org.framework.demo.classloader.RunnerClassLoader || org.framework.demo.classloader.RunnerClassLoader2

aop.factory.enabledAdvisorExpressions = 

